apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goweb

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: goweb
    newName: quay.io/sdavies/goweb
    newTag: latest
